"""
export_stone_towers_images.py — Ryan Lafferty
Exports static images from the Stone Towers story map for Substack.

Outputs:
  _export_images/stone-towers-plan-chart.png  — Plotly bar: tower plan type distribution
  _export_images/danba-osmnx.png              — Danba OSM map (pre-generated; copied if missing)

Also copies to:
  G:/My Drive/02. Obsidian/Lafferty Cloud/Substack/images/stone-towers/

Run from: research/analysis/
    python export_stone_towers_images.py
"""

import os
import shutil
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import plotly.express as px
import plotly.io as pio

OUT_DIR = "_export_images"
DRIVE_DIR = r"G:\My Drive\02. Obsidian\Lafferty Cloud\Substack\images\stone-towers"

os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(DRIVE_DIR, exist_ok=True)


def save(fig, filename):
	local = os.path.join(OUT_DIR, filename)
	drive = os.path.join(DRIVE_DIR, filename)
	pio.write_image(fig, local, scale=2)
	shutil.copy(local, drive)
	size_kb = os.path.getsize(local) // 1024
	print(f"  {filename}  ({size_kb} KB)")


# ---------------------------------------------------------------------------
# 1. Tower Plan Type Distribution
# ---------------------------------------------------------------------------
print("Exporting plan-type distribution chart...")
plan_data = pd.DataFrame([
	{"Plan Type": "Square", "Estimated %": 55, "Tradition": "Qiang + Gyalrong"},
	{"Plan Type": "Hexagonal", "Estimated %": 18, "Tradition": "Gyalrong"},
	{"Plan Type": "Octagonal", "Estimated %": 10, "Tradition": "Gyalrong"},
	{"Plan Type": "Star (5-6 pt)", "Estimated %": 9, "Tradition": "Gyalrong"},
	{"Plan Type": "Star (8-13 pt)", "Estimated %": 8, "Tradition": "Gyalrong (elite)"},
])

fig_plans = px.bar(
	plan_data,
	x="Plan Type",
	y="Estimated %",
	color="Tradition",
	color_discrete_map={
		"Qiang + Gyalrong": "#78716c",
		"Gyalrong": "#a16207",
		"Gyalrong (elite)": "#7c3d12",
	},
	labels={"Estimated %": "Estimated Share (%)"},
	title="Tower Plan Type Distribution",
)
fig_plans.update_layout(
	height=400,
	width=720,
	plot_bgcolor="white",
	paper_bgcolor="#faf8f4",
	margin=dict(l=55, r=30, t=55, b=55),
	font_family="Georgia, serif",
	title_font_size=16,
)
fig_plans.update_traces(marker_line_width=0.5, marker_line_color="white")
save(fig_plans, "stone-towers-plan-chart.png")

# ---------------------------------------------------------------------------
# 2. Copy Danba map (already generated by generate_danba_map.py)
# ---------------------------------------------------------------------------
print("Copying Danba OSM map...")
danba_src = os.path.join(OUT_DIR, "danba-osmnx.png")
danba_dst = os.path.join(DRIVE_DIR, "danba-osmnx.png")
if os.path.exists(danba_src):
	shutil.copy(danba_src, danba_dst)
	size_kb = os.path.getsize(danba_src) // 1024
	print(f"  danba-osmnx.png  ({size_kb} KB)")
else:
	print("  danba-osmnx.png not found — run generate_danba_map.py first")

print("\nDone. Screenshot still needed:")
print("  images/stone-towers/interactive-map.png")
print("  Source: research/_output/analysis/stone-towers.html")
